apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: seaweedfs
  name: seaweedfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs
  template:
    metadata:
      labels:
        app: seaweedfs
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: teng2/seaweedfs:0.2.0
        name: seaweedfs
        command: [ "/seaweedfs/start.sh"]
        securityContext:
          privileged: true 
          capabilities: 
            add:
              - SYS_ADMIN
        resources: 
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - containerPort: 8888
            name: filer
          - containerPort: 18888
            name: filer-gprc
          - containerPort: 8080
            name: volume
          - containerPort: 18080
            name: volume-gprc
          - containerPort: 9333
            name: master
          - containerPort: 19333
            name: master-grpc
          