apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  labels:
    app: seaweedfs
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      name: seaweedfs
  selector:
    app: seaweedfs